name: Build site content

on:
  workflow_call:
    inputs:
      ELEVENTY_HTML_BASE:
        type: string
        required: false
        default: "/"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ELEVENTY_HTML_BASE: ${{ inputs.ELEVENTY_HTML_BASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Restore build cache
        uses: actions/cache/restore@v5
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install packages
        run: |
          npm install
      - name: Build pages
        env:
          CI: "1"
        run: |
          npm run build

      - name: Save build cache
        uses: actions/cache/save@v5
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}

      - name: Upload content artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site
